[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/resume.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment; filename=\"Titus_Vimal_Raj_Resume.pdf\""

[[headers]]
  for = "/Titus_Vimal_Raj_Resume.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Content-Disposition = "attachment; filename=\"Titus_Vimal_Raj_Resume.pdf\""
